-- ============================================================
-- ChainMate: ALL migrations in one file
-- Paste this whole file into the Supabase SQL editor and Run.
-- Safe to run more than once: every statement is idempotent,
-- so re-running never duplicates or destroys anything.
-- Generated by: npm run db:bundle  (do not edit by hand)
-- ============================================================
-- ============================================================
-- 0001_init.sql
-- ============================================================
-- ChainMate — identity & progression schema
-- ===========================================
-- Run this once in your Supabase project (Dashboard → SQL Editor → New query,
-- paste, Run). It is idempotent (safe to run again).
--
-- Design notes:
--  * player_id is the game-store identity (a device guest id or the account's
--    fresh `acct_…` player id). user_id links the profile to Supabase Auth
--    for accounts; guests keep user_id NULL until they create an account.
--    Accounts always start fresh — guest history is never merged, so an
--    account's player_id is never a guest id.
--  * All writes go through the service-role key (bypasses RLS). Clients can
--    only SELECT — they can never edit ratings, results or achievements.

-- ---------------------------------------------------------------------------
-- Profiles
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  player_id text not null unique,
  username text not null,
  is_guest boolean not null default true,
  rating integer not null default 1200,
  peak_rating integer not null default 1200,
  wins integer not null default 0,
  losses integer not null default 0,
  draws integer not null default 0,
  games integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Usernames are unique case-insensitively (ChainMate vs chainmate → conflict).
create unique index if not exists profiles_username_lower_idx
  on public.profiles (lower(username));

-- ---------------------------------------------------------------------------
-- Game history (completed games mirrored from the game store)
-- ---------------------------------------------------------------------------
create table if not exists public.games (
  id text primary key,
  white_player_id text not null,
  black_player_id text not null,
  time_control text,
  status text not null,
  result text,
  winner_player_id text not null default '',
  created_at bigint not null,
  started_at bigint,
  ended_at bigint,
  moves jsonb not null default '[]',
  summary text not null default '',
  synced_at timestamptz not null default now()
);

create index if not exists games_white_idx on public.games (white_player_id);
create index if not exists games_black_idx on public.games (black_player_id);
create index if not exists games_ended_idx on public.games (ended_at desc);

-- ---------------------------------------------------------------------------
-- Achievements (server-written only)
-- ---------------------------------------------------------------------------
create table if not exists public.player_achievements (
  player_id text not null,
  code text not null,
  earned_at bigint not null,
  primary key (player_id, code)
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.player_achievements enable row level security;

-- Public read: profiles (leaderboard, public profiles), games (watch /
-- replay), achievements. No insert/update/delete policies exist — only the
-- service-role key (which bypasses RLS) can write.
-- Postgres has no CREATE POLICY IF NOT EXISTS, so every policy is preceded by
-- a drop guard: re-running this file (via RUN_ALL.sql) stays idempotent.
drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
  on public.profiles for select using (true);

drop policy if exists "games are publicly readable" on public.games;
create policy "games are publicly readable"
  on public.games for select using (true);

drop policy if exists "achievements are publicly readable" on public.player_achievements;
create policy "achievements are publicly readable"
  on public.player_achievements for select using (true);

-- ============================================================
-- 0002_game_snapshots.sql
-- ============================================================
-- ChainMate — durable game snapshots
-- ===================================
-- Run this once in Supabase (Dashboard → SQL Editor → New query → paste → Run).
-- Idempotent — safe to run again.

-- Full game-state snapshot (fen, moves, commentary, draw offers, visibility…)
-- is written on every game mutation, so a live match can be recovered from
-- the database even if the fast game store (KV / file store) loses the game.
-- This is what fixes "Game not found" mid-game on serverless hosts.
alter table public.games add column if not exists snapshot jsonb;

-- Used to rebuild the live Watch feed and the game index after a storage
-- reset (active games for Watch, recent games for Games / homepage).
create index if not exists games_status_idx on public.games (status);
create index if not exists games_created_idx on public.games (created_at desc);

-- ============================================================
-- 0003_identity_social.sql
-- ============================================================
-- ChainMate — identity, rating confidence & social layer
-- ========================================================
-- Run this once in Supabase (Dashboard → SQL Editor → New query → paste → Run).
-- Idempotent — safe to run again.

-- ---------------------------------------------------------------------------
-- Profiles: Glicko rating deviation + optional country
-- ---------------------------------------------------------------------------
-- rd (rating deviation) is the confidence behind a rating: new/inactive
-- players start at 350 (provisional) and settle toward 30 as they play.
-- last_played_at drives RD decay for inactive players. country is optional
-- and purely display (flag next to the username).
alter table public.profiles add column if not exists rd integer not null default 350;
alter table public.profiles add column if not exists last_played_at bigint;
alter table public.profiles add column if not exists country text;

-- ---------------------------------------------------------------------------
-- Friendships (real, persistent friend requests — never local UI state)
-- ---------------------------------------------------------------------------
-- status: pending (awaiting addressee) → accepted | rejected. Both players
-- are identified by their game-store player id so guests and accounts work
-- identically. The pair is unique in both directions (one row per pair).
create table if not exists public.friendships (
  id bigserial primary key,
  requester_player_id text not null,
  addressee_player_id text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at bigint not null,
  responded_at bigint,
  unique (requester_player_id, addressee_player_id)
);

create index if not exists friendships_addressee_idx
  on public.friendships (addressee_player_id, status);

create index if not exists friendships_requester_idx
  on public.friendships (requester_player_id, status);

alter table public.friendships enable row level security;

-- Public read so profiles can render friends lists (writes stay service-role
-- only, like every other trusted table). Drop guard keeps RUN_ALL re-runnable.
drop policy if exists "friendships are publicly readable" on public.friendships;
create policy "friendships are publicly readable"
  on public.friendships for select using (true);

-- ============================================================
-- 0004_profiles_nullable_user_id.sql
-- ============================================================
-- ChainMate — allow guest profiles (user_id nullable)
-- ===================================================
-- Run once in Supabase (Dashboard → SQL Editor → New query, paste, Run).
-- Idempotent: safe to run again.
--
-- Why this exists
-- ---------------
-- 0001_init.sql declares:
--
--   user_id uuid primary key references auth.users (id) on delete cascade
--
-- while its own header comment states "guests keep user_id NULL until they
-- create an account". Both cannot hold — a PRIMARY KEY is implicitly NOT NULL.
-- The comment describes the intent the application code was written against,
-- so the constraint is what's wrong.
--
-- Consequence: upsertProfiles() in lib/supabase/db.ts writes guest rows with
-- player_id/username/rating and no user_id, so every guest profile insert
-- fails with a not-null violation. Guests never get a durable profile row.
--
-- Fix: promote player_id (already `not null unique`) to primary key, and let
-- user_id be a nullable unique column that still references auth.users. This
-- keeps profileForUserId() returning at most one row, and keeps account
-- deletion cascading from auth.users.

-- ---------------------------------------------------------------------------
-- 1. player_id becomes the primary key
-- ---------------------------------------------------------------------------
do $$
begin
  -- Only act if user_id is still the PK, so re-running is a no-op.
  if exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
    where tc.table_schema = 'public'
      and tc.table_name = 'profiles'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name = 'user_id'
  ) then
    -- Guard: player_id must be complete and unique before it can be the PK.
    if exists (select 1 from public.profiles where player_id is null) then
      raise exception 'Cannot repoint primary key: public.profiles has NULL player_id rows';
    end if;

    alter table public.profiles drop constraint profiles_pkey;
    alter table public.profiles add constraint profiles_pkey primary key (player_id);
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 2. user_id becomes nullable
-- ---------------------------------------------------------------------------
-- Dropping the PK above does not clear the NOT NULL that the PK implied.
alter table public.profiles alter column user_id drop not null;

-- ---------------------------------------------------------------------------
-- 3. user_id stays unique (one profile per auth account)
-- ---------------------------------------------------------------------------
-- Postgres permits multiple NULLs in a unique index, so all guest rows coexist
-- while profileForUserId() -> .eq("user_id", …) still matches at most one row.
create unique index if not exists profiles_user_id_key
  on public.profiles (user_id)
  where user_id is not null;

-- ---------------------------------------------------------------------------
-- 4. Keep the auth.users FK (account deletion must still cascade)
-- ---------------------------------------------------------------------------
-- The original FK rode along with the inline `primary key references …` and
-- survives the PK swap, but assert it explicitly so a hand-patched database
-- converges to the same shape. DELETE /api/players/me relies on this cascade.
do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'profiles'
      and constraint_type = 'FOREIGN KEY'
      and constraint_name = 'profiles_user_id_fkey'
  ) then
    alter table public.profiles
      add constraint profiles_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;
end
$$;

-- ============================================================
-- 0005_cascade_player_data.sql
-- ============================================================
-- ChainMate — make account deletion actually cascade
-- ==================================================
-- Run once in Supabase (Dashboard → SQL Editor → New query, paste, Run).
-- Idempotent: safe to run again.
--
-- Run migration 0004 BEFORE this one.
--
-- Why this exists
-- ---------------
-- DELETE /api/players/me documents its behaviour as:
--
--   "Delete Supabase auth user — this cascades to profiles,
--    player_achievements, and friendships via FK constraints."
--
-- Only the first of those was ever true. Before this migration the entire
-- schema contained exactly one foreign key — profiles.user_id → auth.users —
-- so deleting an account removed the auth user and its profile row and left
-- every achievement and friendship behind, keyed to a player_id that no
-- longer resolves to anything. Deleted users kept appearing in other
-- players' friends lists.
--
-- Fix: real FKs from the player-scoped tables to profiles(player_id), with
-- ON DELETE CASCADE. profiles.player_id is `not null unique` in 0001 (and the
-- primary key after 0004), so it is a valid FK target either way. The delete
-- chain becomes:
--
--   auth.users → profiles → { player_achievements, friendships }
--
-- Note on public.games
-- --------------------
-- games is deliberately NOT given a cascading FK. A game is a shared record
-- between two players: cascading from one would destroy the opponent's
-- history too, and /watch and /games replay finished games indefinitely.
-- winner_player_id also defaults to '' (empty string, for draws/unfinished),
-- which no profile row can ever match, so it cannot carry an FK at all.
-- Game history intentionally outlives the accounts that produced it.

-- ---------------------------------------------------------------------------
-- 1. Report pre-existing orphans
-- ---------------------------------------------------------------------------
-- Rows whose player_id has no profiles row. These exist because the 0001
-- schema made guest profile inserts impossible (see 0004), so guest-owned
-- achievements and friendships were written with no profile to point at.
-- The counts are printed rather than acted on — nothing here deletes data.
do $$
declare
  orphan_ach integer;
  orphan_req integer;
  orphan_addr integer;
begin
  select count(*) into orphan_ach
    from public.player_achievements a
    where not exists (select 1 from public.profiles p where p.player_id = a.player_id);

  select count(*) into orphan_req
    from public.friendships f
    where not exists (select 1 from public.profiles p where p.player_id = f.requester_player_id);

  select count(*) into orphan_addr
    from public.friendships f
    where not exists (select 1 from public.profiles p where p.player_id = f.addressee_player_id);

  raise notice 'Orphaned rows — player_achievements: %, friendships.requester: %, friendships.addressee: %',
    orphan_ach, orphan_req, orphan_addr;

  if orphan_ach + orphan_req + orphan_addr > 0 then
    raise notice 'Constraints are added NOT VALID, so these rows are left in place. See step 3 to review and clean them up.';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 2. Add the cascading foreign keys
-- ---------------------------------------------------------------------------
-- NOT VALID is deliberate: it skips the one-time check against existing rows
-- (so this migration cannot fail on the orphans reported above and never
-- destroys data) while still enforcing the constraint on every subsequent
-- insert and update. ON DELETE CASCADE is a referential action and fires
-- regardless of validation state, so account deletion cascades correctly the
-- moment this runs — which is the bug being fixed.
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'player_achievements'
      and constraint_type = 'FOREIGN KEY'
      and constraint_name = 'player_achievements_player_id_fkey'
  ) then
    alter table public.player_achievements
      add constraint player_achievements_player_id_fkey
      foreign key (player_id) references public.profiles (player_id)
      on delete cascade
      not valid;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'friendships'
      and constraint_type = 'FOREIGN KEY'
      and constraint_name = 'friendships_requester_player_id_fkey'
  ) then
    alter table public.friendships
      add constraint friendships_requester_player_id_fkey
      foreign key (requester_player_id) references public.profiles (player_id)
      on delete cascade
      not valid;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'friendships'
      and constraint_type = 'FOREIGN KEY'
      and constraint_name = 'friendships_addressee_player_id_fkey'
  ) then
    alter table public.friendships
      add constraint friendships_addressee_player_id_fkey
      foreign key (addressee_player_id) references public.profiles (player_id)
      on delete cascade
      not valid;
  end if;
end
$$;

-- Supporting index for the achievements FK. friendships already has
-- friendships_requester_idx and friendships_addressee_idx from 0003; without
-- an index on the referencing column, every profile delete forces a
-- sequential scan of the child table.
create index if not exists player_achievements_player_id_idx
  on public.player_achievements (player_id);

-- ---------------------------------------------------------------------------
-- 3. Optional: clean up orphans and fully validate (review before running)
-- ---------------------------------------------------------------------------
-- Left commented out on purpose — it deletes rows. Run step 1's counts first,
-- inspect anything non-zero with the SELECTs below, and only then uncomment.
-- Until validated the constraints are still enforced for all new writes and
-- still cascade; validating only closes the historical gap.
--
-- -- Inspect first:
-- select * from public.player_achievements a
--   where not exists (select 1 from public.profiles p where p.player_id = a.player_id);
-- select * from public.friendships f
--   where not exists (select 1 from public.profiles p where p.player_id = f.requester_player_id)
--      or not exists (select 1 from public.profiles p where p.player_id = f.addressee_player_id);
--
-- -- Then delete and validate:
-- delete from public.player_achievements a
--   where not exists (select 1 from public.profiles p where p.player_id = a.player_id);
-- delete from public.friendships f
--   where not exists (select 1 from public.profiles p where p.player_id = f.requester_player_id)
--      or not exists (select 1 from public.profiles p where p.player_id = f.addressee_player_id);
--
-- alter table public.player_achievements validate constraint player_achievements_player_id_fkey;
-- alter table public.friendships validate constraint friendships_requester_player_id_fkey;
-- alter table public.friendships validate constraint friendships_addressee_player_id_fkey;

-- ============================================================
-- 0006_tournaments.sql
-- ============================================================
-- ChainMate — Tournament engine (Phase 2A: free tournaments only)
-- ================================================================
-- Idempotent, additive. Pairs with lib/server/tournament-store.ts, which
-- mirrors the fast-store tournament documents here best-effort; the fast
-- store (KV / file store) stays the source of truth at runtime and this
-- schema is the cold-start recovery + durable record layer.
--
-- PAYMENT BOUNDARY: `tournaments.entry_fee_nim` is a nullable RESERVED
-- column for Phase 2B. Nothing in this phase writes or reads it — every row
-- carries NULL. There are no balances, no prize pools, no payouts, and no
-- wallet fields anywhere in this migration.

-- ---------------------------------------------------------------------------
-- Tournaments
-- ---------------------------------------------------------------------------
create table if not exists public.tournaments (
  id text primary key,
  name text not null,
  description text not null default '',
  creator_player_id text not null,
  format text not null check (format in ('knockout', 'swiss', 'arena')),
  time_control text not null,
  max_players integer not null check (max_players between 2 and 128),
  status text not null check (status in
    ('draft', 'registration', 'locked', 'in_progress', 'completed', 'cancelled')),
  swiss_rounds integer,
  registration_closes_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  current_round integer not null default 0,
  total_rounds integer not null default 0,
  winner_player_id text,
  -- Phase 2B reservation. Nullable, never written by Phase 2A code.
  entry_fee_nim numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tournaments_status_idx
  on public.tournaments (status);
create index if not exists tournaments_creator_idx
  on public.tournaments (creator_player_id);
create index if not exists tournaments_created_idx
  on public.tournaments (created_at desc);

-- ---------------------------------------------------------------------------
-- Tournament entries (join records; one row per player per tournament)
-- ---------------------------------------------------------------------------
create table if not exists public.tournament_entries (
  tournament_id text not null references public.tournaments (id) on delete cascade,
  player_id text not null,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  withdrawn boolean not null default false,
  primary key (tournament_id, player_id)
);

create index if not exists tournament_entries_player_idx
  on public.tournament_entries (player_id);

-- ---------------------------------------------------------------------------
-- Tournament matches (each references an existing hosted ChainMate game)
-- ---------------------------------------------------------------------------
create table if not exists public.tournament_matches (
  id text primary key,
  tournament_id text not null references public.tournaments (id) on delete cascade,
  round integer not null default 0,
  slot integer not null default 0,
  white_player_id text not null,
  black_player_id text not null,
  game_id text not null default '',
  status text not null default 'active' check (status in ('pending', 'active', 'complete')),
  result text check (result in ('white', 'black', 'draw')),
  result_reason text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists tournament_matches_tournament_idx
  on public.tournament_matches (tournament_id, round, slot);
create index if not exists tournament_matches_game_idx
  on public.tournament_matches (game_id);

-- ---------------------------------------------------------------------------
-- Standings snapshot (the server's last computed table per tournament)
-- ---------------------------------------------------------------------------
create table if not exists public.tournament_standings (
  tournament_id text primary key references public.tournaments (id) on delete cascade,
  standings jsonb not null default '[]',
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security — same model as the rest of ChainMate: public read,
-- service-role-only writes (all tournament mutations go through the API,
-- which authenticates with resolveActingPlayer and writes with the admin key).
-- ---------------------------------------------------------------------------
alter table public.tournaments enable row level security;
alter table public.tournament_entries enable row level security;
alter table public.tournament_matches enable row level security;
alter table public.tournament_standings enable row level security;

drop policy if exists "tournaments are publicly readable" on public.tournaments;
create policy "tournaments are publicly readable"
  on public.tournaments for select using (true);

drop policy if exists "tournament entries are publicly readable" on public.tournament_entries;
create policy "tournament entries are publicly readable"
  on public.tournament_entries for select using (true);

drop policy if exists "tournament matches are publicly readable" on public.tournament_matches;
create policy "tournament matches are publicly readable"
  on public.tournament_matches for select using (true);

drop policy if exists "tournament standings are publicly readable" on public.tournament_standings;
create policy "tournament standings are publicly readable"
  on public.tournament_standings for select using (true);

-- ============================================================
-- 0007_nimiq_wallet_binding.sql
-- ============================================================
-- ChainMate — Nimiq wallet identity binding (Phase 1B)
-- =====================================================
-- Idempotent, additive. Pairs with lib/server/nimiq/store.ts, which keeps the
-- fast store (KV / file store) as the runtime source of truth and mirrors
-- bindings + challenges here best-effort; this schema is the durable record
-- layer and the cold-start recovery source for the address-uniqueness index.
--
-- SCOPE BOUNDARY: identity binding only. There are no balances, transactions,
-- deposits, withdrawals, prizes, payouts, or treasury tables here — those
-- belong to later phases and none are reserved by this migration.
--
-- Public key is kept for verification/audit: the bound address must always be
-- the Blake2b-256-derived address OF this public key (re-derivable offline).

-- ---------------------------------------------------------------------------
-- One wallet per player (player_id is the primary key), one player per wallet
-- (address is globally unique). Canonical address form: uppercase, spaces
-- stripped (36 chars, "NQ" + 2 check digits + 32 base32 chars).
-- ---------------------------------------------------------------------------
create table if not exists public.nimiq_wallet_bindings (
  player_id text primary key references public.profiles (player_id) on delete cascade,
  address text not null unique,
  network text not null check (network in ('main', 'test')),
  public_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists nimiq_wallet_bindings_network_idx
  on public.nimiq_wallet_bindings (network);

-- ---------------------------------------------------------------------------
-- Server-issued, single-use link challenges. A challenge is cryptographically
-- random (32 bytes, hex-encoded), bound to one player + one network, and
-- consumed exactly once within its short expiry window. Only the service role
-- reads/writes this table: RLS is enabled with NO policies, so anon and
-- authenticated clients are denied while the API (service key) proceeds.
-- ---------------------------------------------------------------------------
create table if not exists public.nimiq_wallet_challenges (
  nonce text primary key,
  player_id text not null references public.profiles (player_id) on delete cascade,
  network text not null check (network in ('main', 'test')),
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create index if not exists nimiq_wallet_challenges_player_idx
  on public.nimiq_wallet_challenges (player_id);
create index if not exists nimiq_wallet_challenges_expiry_idx
  on public.nimiq_wallet_challenges (expires_at);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.nimiq_wallet_bindings enable row level security;
alter table public.nimiq_wallet_challenges enable row level security;

-- Bindings are public read (a wallet address is public chain data, and the
-- app's profiles/leaderboard are public too); every write goes through the
-- authenticated API with the service-role key. Drop guard keeps RUN_ALL
-- re-runnable.
drop policy if exists "nimiq wallet bindings are publicly readable" on public.nimiq_wallet_bindings;
create policy "nimiq wallet bindings are publicly readable"
  on public.nimiq_wallet_bindings for select using (true);

-- Challenges carry single-use secrets: no client-facing policies at all.

-- ============================================================
-- 0008_nimiq_transactions.sql
-- ============================================================
-- ChainMate — Nimiq transaction consumption ledger (Phase 1C)
-- ===========================================================
-- Idempotent, additive. Pairs with lib/server/nimiq/transactions.ts, which
-- verifies a REAL transaction through the configured Nimiq node and records
-- it here exactly once. This table is REPLAY PROTECTION + AUDIT only:
--
--   * no balances, no credits, no custodial ledger
--   * no payouts, no prize accounting, no treasury movements
--   * rows are written only after every verification check passes
--
-- The UNIQUE (network, tx_hash) constraint is the final durable protection
-- against accepting the same on-chain transaction twice — it holds across
-- server instances and restarts, unlike any in-memory set.

create table if not exists public.nimiq_transactions (
  id bigserial primary key,
  network text not null check (network in ('main', 'test')),
  -- Canonical tx hash as returned by the node (lowercase hex).
  tx_hash text not null,
  player_id text not null references public.profiles (player_id) on delete cascade,
  -- What the transaction was consumed FOR. Phase 1C only ever writes
  -- 'verification'; tournament entry fees (2B) will write 'tournament_entry'.
  kind text not null default 'verification'
    check (kind in ('verification', 'tournament_entry')),
  -- Reserved for Phase 2B: which tournament a consumed transaction paid for.
  -- Nullable; never written by Phase 1C code.
  tournament_id text,
  sender text not null,
  recipient text not null,
  -- Luna as an EXACT decimal string (digits only, no sign, no exponent).
  -- Never numeric/float: luna must survive JSON round-trips bit-exact.
  amount_luna text not null check (amount_luna ~ '^[0-9]+$'),
  block_number bigint not null check (block_number >= 0),
  -- Confirmations observed at verification time (audit snapshot).
  confirmations integer not null check (confirmations >= 0),
  verified_at timestamptz not null default now(),
  consumed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  -- The durable replay guard: one consumption per on-chain transaction
  -- per network (main/test hashes could theoretically collide).
  unique (network, tx_hash)
);

create index if not exists nimiq_transactions_player_idx
  on public.nimiq_transactions (player_id);
create index if not exists nimiq_transactions_kind_idx
  on public.nimiq_transactions (kind);
-- Future tournament lookup: "which entries paid for tournament X?"
create index if not exists nimiq_transactions_tournament_idx
  on public.nimiq_transactions (tournament_id)
  where tournament_id is not null;
create index if not exists nimiq_transactions_created_idx
  on public.nimiq_transactions (created_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security — service-role only writes (all consumption flows through
-- the authenticated API); read access is deliberately withheld from clients:
-- consumption records contain treasury flows and must not be enumerable.
-- ---------------------------------------------------------------------------
alter table public.nimiq_transactions enable row level security;

-- ============================================================
-- 0009_nimiq_tournament_economy.sql
-- ============================================================
-- ChainMate — Nimiq tournament economy (Phase 2B)
-- ================================================
-- Idempotent, additive. Builds on 0006 (tournaments), 0007 (wallet
-- bindings), 0008 (nimiq_transactions consumption ledger). Adds:
--
--   1. paid-tournament fields on public.tournaments
--      (entry fee in EXACT luna text, distribution preset, payout state)
--   2. durable uniqueness so a verified tx can pay for ONE tournament entry
--      exactly once (partial unique indexes over kind='tournament_entry')
--   3. public.tournament_payouts — the durable payout ledger / state machine
--
-- FINANCIAL INVARIANTS ENFORCED BY SCHEMA (not just code):
--   * a tx hash pays for at most one tournament entry (per network)
--   * a player has at most one paid entry per tournament
--   * luna is stored as digits-only text — never numeric/float
--   * payout amount >= 0; payouts are per tournament+player, one row each
--
-- There are NO balances, NO custodial ledger, NO fake money anywhere here.
-- Every luna value originates from a REAL on-chain tx verified through
-- verifyIncomingTransaction() (Phase 1C) before any row is written.

-- ---------------------------------------------------------------------------
-- 1. Paid tournament fields
-- ---------------------------------------------------------------------------
alter table public.tournaments
  add column if not exists entry_fee_luna text
    check (entry_fee_luna ~ '^[0-9]+$'),           -- digits-only, exact luna
  add column if not exists entry_fee_nim decimal(12, 5), -- human display copy
  add column if not exists prize_preset text
    check (prize_preset in ('winner', 'top3', 'top5')),
  add column if not exists payout_status text
    not null default 'none'
    check (payout_status in
      ('none', 'pending', 'partial', 'paid', 'refund_required'));

-- The old reserved column (0006) is superseded by the exact-luna column.
-- Keep it for drift safety but stop using it; drop it from new mental models.
comment on column public.tournaments.entry_fee_nim is
  'DEPRECATED Phase-2A reservation — display copy only; entry_fee_luna is authoritative.';

-- ---------------------------------------------------------------------------
-- 2. Entry-ledger uniqueness (durable, partial unique indexes on 0008 table)
-- ---------------------------------------------------------------------------
-- (a) One tx consumed as a tournament entry, ever (per network).
create unique index if not exists nimiq_tx_one_entry_per_tx
  on public.nimiq_transactions (network, tx_hash)
  where kind = 'tournament_entry';

-- (b) A tournament+tx pair can appear once (tx can't pay two tournaments).
--     Implied by (a), kept explicit for documentation value.
-- (c) One PAID entry per player per tournament.
create unique index if not exists nimiq_tx_one_entry_per_player
  on public.nimiq_transactions (tournament_id, player_id)
  where kind = 'tournament_entry' and tournament_id is not null;

-- Tournament lookup for prize-pool queries.
create index if not exists nimiq_tx_tournament_entry_idx
  on public.nimiq_transactions (tournament_id, created_at)
  where kind = 'tournament_entry';

-- ---------------------------------------------------------------------------
-- 3. Payout ledger — durable state machine
-- ---------------------------------------------------------------------------
create table if not exists public.tournament_payouts (
  id bigserial primary key,
  tournament_id text not null
    references public.tournaments (id) on delete cascade,
  player_id text not null,
  -- Final standings rank this payout is for (1 = winner).
  payout_rank integer not null check (payout_rank >= 1),
  -- Share in basis points (10000 = 100%). Exact, never a float.
  share_bps integer not null check (share_bps between 0 and 10000),
  -- Exact luna, digits-only text.
  amount_luna text not null check (amount_luna ~ '^[0-9]+$'),
  -- Where the funds go: ALWAYS the Phase-1B verified binding, never a
  -- client-supplied address. Nullable while blocked_no_wallet.
  destination_address text,
  -- PENDING → SENT → VERIFIED; or BLOCKED_NO_WALLET; or FAILED (retryable).
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'verified', 'failed', 'blocked_no_wallet')),
  -- On-chain hash of the OUTGOING treasury payout, once one exists.
  -- NULL until a real signer is configured — never faked.
  payout_tx_hash text,
  sent_at timestamptz,
  verified_at timestamptz,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- One payout row per tournament per player.
  unique (tournament_id, player_id)
);

create index if not exists tournament_payouts_tournament_idx
  on public.tournament_payouts (tournament_id, payout_rank);
create index if not exists tournament_payouts_status_idx
  on public.tournament_payouts (status);
create index if not exists tournament_payouts_player_idx
  on public.tournament_payouts (player_id);

-- RLS: payouts contain treasury flows — read withheld from clients, writes
-- service-role only (all flows go through the authenticated API).
alter table public.tournament_payouts enable row level security;

-- Guard: a payout row can never be marked sent/verified without a real tx
-- hash. (Application code also enforces this; the check is the durable net.)
alter table public.tournament_payouts
  add constraint payout_sent_requires_hash
  check (
    (status in ('sent', 'verified')) = (payout_tx_hash is not null)
  );

-- ============================================================
-- 0010_payout_dispatch.sql
-- ============================================================
-- ChainMate — treasury payout dispatch (Phase 3B)
-- ================================================
-- Idempotent, additive. Builds on 0009 (tournament_payouts state machine).
-- Gives the payout ledger the durable metadata a REAL on-chain dispatch
-- needs, so a crash at any point can be recovered without ever paying twice:
--
--   network                 which chain this payout dispatch ran on
--   sender_address          the treasury address the node signs from
--   validity_start_height   the WRITE-AHEAD dispatch record — see below
--   dispatch_attempts       how many broadcast attempts were made
--   last_broadcast_at       when the most recent attempt was sent
--   status 'dispatching'    broadcast intent recorded, outcome unknown
--
-- THE CRASH-SAFETY STORY (why validity_start_height is the whole point):
-- Nimiq transactions are a PURE function of their fields — sender, recipient,
-- value, fee, validity_start_height, network — and ed25519 signing is
-- deterministic (RFC 8032). Two broadcasts with identical fields produce a
-- byte-identical transaction and therefore the SAME hash; the chain itself
-- rejects/ignores the duplicate (mempool dedupe + validity-store replay
-- window). So the recovery protocol after a crash between "broadcast sent"
-- and "hash persisted" is to re-broadcast with the SAME recorded
-- validity_start_height: either the original went out (duplicate is deduped
-- on-chain) or it never left (this is its first broadcast). Either way,
-- EXACTLY ONE effective payment exists. No hash guessing, no balance math.

-- ---------------------------------------------------------------------------
-- 1. Dispatch metadata columns
-- ---------------------------------------------------------------------------
alter table public.tournament_payouts
  add column if not exists network text
    check (network in ('main', 'test')),
  add column if not exists sender_address text,
  add column if not exists validity_start_height integer
    check (validity_start_height >= 0),
  add column if not exists dispatch_attempts integer not null default 0
    check (dispatch_attempts >= 0),
  add column if not exists last_broadcast_at timestamptz;

-- ---------------------------------------------------------------------------
-- 2. Extend the status state machine with the write-ahead 'dispatching' state
--    (0009 declared the check inline, so its name is generated — look it up.)
-- ---------------------------------------------------------------------------
do $$
declare
  r record;
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tournament_payouts_status_check'
      and conrelid = 'public.tournament_payouts'::regclass
  ) then
    -- The generated name differs; find whichever check constrains status.
    for r in
      select conname from pg_constraint
      where conrelid = 'public.tournament_payouts'::regclass
        and contype = 'c'
        and pg_get_constraintdef(oid) like '%status%'
        and pg_get_constraintdef(oid) like '%pending%'
    loop
      execute format('alter table public.tournament_payouts drop constraint %I', r.conname);
      exit;
    end loop;
  else
    alter table public.tournament_payouts
      drop constraint tournament_payouts_status_check;
  end if;
end $$;

alter table public.tournament_payouts
  add constraint tournament_payouts_status_check
  check (status in
    ('pending', 'dispatching', 'sent', 'verified', 'failed', 'blocked_no_wallet'));

-- A 'dispatching' row is a broadcast INTENT: it must already know exactly what
-- it intends to send — destination, amount, sender, validity start height.
alter table public.tournament_payouts
  add constraint payout_dispatching_is_complete_intent
  check (
    status <> 'dispatching'
    or (
      destination_address is not null
      and amount_luna is not null
      and sender_address is not null
      and validity_start_height is not null
    )
  );

-- ---------------------------------------------------------------------------
-- 3. Durable duplicate protection: an outgoing payout hash can be used ONCE
--    per network, ever. Combined with the entry-ledger uniqueness this makes
--    "same tx pays twice" impossible at the schema level, not just in code.
-- ---------------------------------------------------------------------------
create unique index if not exists tournament_payouts_tx_hash_unique
  on public.tournament_payouts (network, payout_tx_hash)
  where payout_tx_hash is not null;

-- Fast lookup for the reconciler: everything currently mid-dispatch.
create index if not exists tournament_payouts_dispatching_idx
  on public.tournament_payouts (status)
  where status = 'dispatching';

-- ============================================================
-- 0011_avatars.sql
-- ============================================================
-- ChainMate — profile pictures (avatars)
-- ================================================
-- Idempotent, additive.
--
--   1. profiles.avatar_url — the public URL of the player's picture
--   2. the public `avatars` storage bucket the upload route writes to
--
-- No RLS policies are needed for the app: every upload goes through the
-- server route with the service-role key, and reads use the bucket's public
-- URL. The bucket must be PUBLIC so <img> tags can load the pictures.

alter table public.profiles
  add column if not exists avatar_url text;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

-- ============================================================
-- 0011_tournament_schedule.sql
-- ============================================================
-- ChainMate — tournament scheduling + host delete
-- ================================================
-- Idempotent, additive. Adds the scheduled-start instant (host picks a
-- future time; registration opens automatically when it arrives) to the
-- durable mirror of the tournament document. No payment semantics here.

alter table public.tournaments
  add column if not exists scheduled_start_at timestamptz;

-- ============================================================
-- 0012_tournament_lifecycle.sql
-- ============================================================
-- ChainMate — tournament lifecycle completion (deadline, minimum field,
-- refunds, arena window, knockout tiebreaks)
-- ============================================================================
-- Idempotent, additive. Builds on 0006/0009/0010/0011_schedule. Adds:
--
--   1. tournaments.scheduled_end_at   — arena (and any format's) hard end
--   2. tournaments.cancel_reason      — why an event was cancelled
--   3. tournaments.min_players        — deadline rule: max(2, prize positions)
--   4. tournaments.payout_status gains 'refunded' (fully refunded cancellation)
--   5. public.tournament_refunds — the durable refund ledger
--
-- REFUND FINANCIAL INVARIANTS (schema-level, like 0009/0010):
--   * one refund row per (tournament, player) — a retry cannot create two
--   * one refund per entry tx — the money returns exactly once
--   * amount equals the verified entry amount (digits-only luna, exact)
--   * status machine: owed → dispatched → verified (failed is retryable back
--     to owed; 'dispatched' is the write-ahead intent, see 0010's protocol)
-- ============================================================================

alter table public.tournaments
  add column if not exists scheduled_end_at timestamptz,
  add column if not exists cancel_reason text,
  add column if not exists min_players integer
    check (min_players is null or min_players >= 0);

-- Extend the aggregate payout status with the fully-refunded state.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'tournaments_payout_status_check'
      and conrelid = 'public.tournaments'::regclass
  ) then
    alter table public.tournaments
      drop constraint tournaments_payout_status_check;
  elsif exists (
    select 1 from pg_constraint
    where conrelid = 'public.tournaments'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%payout_status%'
  ) then
    -- 0009 declared the check inline with a generated name: drop whichever
    -- check constrains payout_status.
    declare
      r record;
    begin
      for r in
        select conname from pg_constraint
        where conrelid = 'public.tournaments'::regclass
          and contype = 'c'
          and pg_get_constraintdef(oid) like '%payout_status%'
      loop
        execute format('alter table public.tournaments drop constraint %I', r.conname);
        exit;
      end loop;
    end;
  end if;
end $$;

alter table public.tournaments
  add constraint tournaments_payout_status_check
  check (payout_status in
    ('none', 'pending', 'partial', 'paid', 'refund_required', 'refunded'));

-- The durable refund ledger.
create table if not exists public.tournament_refunds (
  id bigserial primary key,
  tournament_id text not null
    references public.tournaments (id) on delete cascade,
  player_id text not null,
  -- The verified entry tx this refund returns (from nimiq_transactions).
  entry_tx_hash text not null,
  -- Exact luna returned: always exactly what the entry paid.
  amount_luna text not null check (amount_luna ~ '^[0-9]+$'),
  -- OWED → DISPATCHED → VERIFIED; FAILED is retryable back to owed.
  status text not null default 'owed'
    check (status in ('owed', 'dispatched', 'verified', 'failed')),
  refund_tx_hash text,
  validity_start_height integer,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

-- Refund records are who was paid back and how much: financial data. RLS on,
-- no policies, so anon/authenticated clients can read nothing directly; the
-- service role (the only writer/reader, via the server routes) bypasses RLS.
alter table public.tournament_refunds enable row level security;

-- One refund per player per tournament, ever.
create unique index if not exists tournament_refunds_one_per_player
  on public.tournament_refunds (tournament_id, player_id);

-- One refund per entry tx, ever (the same payment cannot be refunded twice,
-- even across tournaments — an entry tx pays one tournament, so this is
-- belt-and-braces over the (tournament, player) uniqueness).
create unique index if not exists tournament_refunds_one_per_tx
  on public.tournament_refunds (entry_tx_hash);

-- Dispatch queue lookup for the reconciler.
create index if not exists tournament_refunds_owed_idx
  on public.tournament_refunds (tournament_id, status)
  where status in ('owed', 'dispatching', 'dispatched');

-- ============================================================
-- 0013_tournament_auto_start.sql
-- ============================================================
-- ChainMate — tournament auto-start-when-full flag
-- ============================================================
-- Idempotent, additive. Builds on 0006/0009/0010/0011/0012.
--
-- start_when_full records the host's choice at creation: when the field
-- reaches maxPlayers during registration the engine locks the field and
-- starts the event immediately (instead of waiting for the scheduled start
-- or a manual host action). Default FALSE — the historical behaviour
-- ("Full — starts when registration closes") is preserved for existing rows.

alter table public.tournaments
  add column if not exists start_when_full boolean not null default false;

-- ============================================================
-- 0014_heal_guest_flags.sql
-- ============================================================
-- ChainMate — heal accounts demoted to guests by the old stats-mirror bug
-- ============================================================
-- Idempotent. The stats mirror once wrote is_guest: true over real account
-- rows (fixed in code, but the flipped rows stayed flipped), which drained
-- the admin's registered-user count and the account list toward zero.
--
-- The predicate is exact: a profile bound to a Supabase auth user
-- (user_id NOT NULL) is by definition a registered account. Guest rows
-- always carry user_id NULL (migration 0004), so this can never promote a
-- guest. Re-running updates zero rows.

update public.profiles
set is_guest = false
where user_id is not null
  and is_guest is true;
